// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.7
//   protoc               v5.28.3
// source: com/ecommerceapp/v1/users.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Timestamp } from "../../../google/protobuf/timestamp";

export const protobufPackage = "com.ecommerceapp.v1.users";

export enum Gender {
  GENDER_UNSPECIFIED = 0,
  GENDER_MALE = 1,
  GENDER_FEMALE = 2,
  GENDER_OTHER = 3,
  UNRECOGNIZED = -1,
}

export function genderFromJSON(object: any): Gender {
  switch (object) {
    case 0:
    case "GENDER_UNSPECIFIED":
      return Gender.GENDER_UNSPECIFIED;
    case 1:
    case "GENDER_MALE":
      return Gender.GENDER_MALE;
    case 2:
    case "GENDER_FEMALE":
      return Gender.GENDER_FEMALE;
    case 3:
    case "GENDER_OTHER":
      return Gender.GENDER_OTHER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Gender.UNRECOGNIZED;
  }
}

export function genderToJSON(object: Gender): string {
  switch (object) {
    case Gender.GENDER_UNSPECIFIED:
      return "GENDER_UNSPECIFIED";
    case Gender.GENDER_MALE:
      return "GENDER_MALE";
    case Gender.GENDER_FEMALE:
      return "GENDER_FEMALE";
    case Gender.GENDER_OTHER:
      return "GENDER_OTHER";
    case Gender.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Role Enum */
export enum Role {
  ROLE_UNSPECIFIED = 0,
  ROLE_CUSTOMER = 1,
  ROLE_SHIPPER = 2,
  ROLE_SHOPOWNER = 3,
  UNRECOGNIZED = -1,
}

export function roleFromJSON(object: any): Role {
  switch (object) {
    case 0:
    case "ROLE_UNSPECIFIED":
      return Role.ROLE_UNSPECIFIED;
    case 1:
    case "ROLE_CUSTOMER":
      return Role.ROLE_CUSTOMER;
    case 2:
    case "ROLE_SHIPPER":
      return Role.ROLE_SHIPPER;
    case 3:
    case "ROLE_SHOPOWNER":
      return Role.ROLE_SHOPOWNER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Role.UNRECOGNIZED;
  }
}

export function roleToJSON(object: Role): string {
  switch (object) {
    case Role.ROLE_UNSPECIFIED:
      return "ROLE_UNSPECIFIED";
    case Role.ROLE_CUSTOMER:
      return "ROLE_CUSTOMER";
    case Role.ROLE_SHIPPER:
      return "ROLE_SHIPPER";
    case Role.ROLE_SHOPOWNER:
      return "ROLE_SHOPOWNER";
    case Role.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface UserId {
  userId: string;
}

export interface CreateUserRequest {
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  username: string;
  password: string;
  addressLine1: string;
  addressLine2: string;
  city: string;
  nation: string;
  gender: Gender;
  role: Role;
  dateOfBirth:
    | Date
    | undefined;
  /** Optional fields for one-to-one relationships */
  customer?: CreateCustomerCommand | undefined;
  shipper?: CreateShipperCommand | undefined;
  shopOwner?: CreateCustomerCommand | undefined;
}

/** Define fields for Customer here if needed */
export interface CreateCustomerCommand {
}

/** Define fields for ShopOwner here if needed */
export interface CreateShopOwnerCommand {
}

export interface CreateShipperCommand {
  /** Define fields for Shipper here if needed */
  shipmentInventoryId: string;
}

export interface Customer {
  /** Define fields for Customer here if needed */
  point: number;
}

export interface Shipper {
  /** Define fields for Shipper here if needed */
  shipmentInventoryId: string;
}

export interface ShopOwner {
  /** Define fields for ShopOwner here if needed */
  numOfShop: number;
}

export interface CreateUserResponse {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  username: string;
  addressLine1: string;
  addressLine2?: string | undefined;
  city: string;
  nation: string;
  gender: Gender;
  role: Role;
  dateOfBirth: Date | undefined;
  customer?: Customer | undefined;
  shipper?: Shipper | undefined;
  shopOwner?: ShopOwner | undefined;
}

export interface UpdateUserInfoRequest {
  firstName?: string | undefined;
  lastName?: string | undefined;
  phoneNumber?: string | undefined;
  addressLine1?: string | undefined;
  addressLine2?: string | undefined;
  city?: string | undefined;
  nation?: string | undefined;
  gender?: Gender | undefined;
  role?: Role | undefined;
  dateOfBirth?: Date | undefined;
  customer?: UpdateCustomerRequest | undefined;
  shipper?: UpdateShipperRequest | undefined;
  shopOwner?: UpdateShopOwnerRequest | undefined;
}

export interface UpdateCustomerRequest {
}

export interface UpdateShipperRequest {
  shipmentInventoryId?: string | undefined;
}

export interface UpdateShopOwnerRequest {
}

export interface UpdateUserRequest {
  userId: UserId | undefined;
  updateInfo: UpdateUserInfoRequest | undefined;
}

export interface UpdateUserResponse {
  id: string;
  firstName: string;
  lastName: string;
  phoneNumber: string;
  addressLine1: string;
  addressLine2?: string | undefined;
  city: string;
  nation: string;
  gender: Gender;
  role: Role;
  dateOfBirth: Date | undefined;
  customer?: Customer | undefined;
  shipper?: Shipper | undefined;
  shopOwner?: ShopOwner | undefined;
}

export interface ChangePasswordRequest {
  userId: string;
  oldPassword: string;
  newPassword: string;
}

export interface UpdateRefreshTokenRequest {
  userId: string;
  refreshToken: string;
}

export interface ValidateUserRequest {
  username: string;
  password: string;
}

export interface Empty {
}

function createBaseUserId(): UserId {
  return { userId: "" };
}

export const UserId: MessageFns<UserId> = {
  encode(message: UserId, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserId {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserId();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserId {
    return { userId: isSet(object.userId) ? globalThis.String(object.userId) : "" };
  },

  toJSON(message: UserId): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserId>, I>>(base?: I): UserId {
    return UserId.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserId>, I>>(object: I): UserId {
    const message = createBaseUserId();
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseCreateUserRequest(): CreateUserRequest {
  return {
    firstName: "",
    lastName: "",
    email: "",
    phoneNumber: "",
    username: "",
    password: "",
    addressLine1: "",
    addressLine2: "",
    city: "",
    nation: "",
    gender: 0,
    role: 0,
    dateOfBirth: undefined,
    customer: undefined,
    shipper: undefined,
    shopOwner: undefined,
  };
}

export const CreateUserRequest: MessageFns<CreateUserRequest> = {
  encode(message: CreateUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.firstName !== "") {
      writer.uint32(10).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(18).string(message.lastName);
    }
    if (message.email !== "") {
      writer.uint32(26).string(message.email);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(34).string(message.phoneNumber);
    }
    if (message.username !== "") {
      writer.uint32(42).string(message.username);
    }
    if (message.password !== "") {
      writer.uint32(50).string(message.password);
    }
    if (message.addressLine1 !== "") {
      writer.uint32(58).string(message.addressLine1);
    }
    if (message.addressLine2 !== "") {
      writer.uint32(66).string(message.addressLine2);
    }
    if (message.city !== "") {
      writer.uint32(74).string(message.city);
    }
    if (message.nation !== "") {
      writer.uint32(82).string(message.nation);
    }
    if (message.gender !== 0) {
      writer.uint32(88).int32(message.gender);
    }
    if (message.role !== 0) {
      writer.uint32(96).int32(message.role);
    }
    if (message.dateOfBirth !== undefined) {
      Timestamp.encode(toTimestamp(message.dateOfBirth), writer.uint32(106).fork()).join();
    }
    if (message.customer !== undefined) {
      CreateCustomerCommand.encode(message.customer, writer.uint32(114).fork()).join();
    }
    if (message.shipper !== undefined) {
      CreateShipperCommand.encode(message.shipper, writer.uint32(122).fork()).join();
    }
    if (message.shopOwner !== undefined) {
      CreateCustomerCommand.encode(message.shopOwner, writer.uint32(130).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.addressLine1 = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.addressLine2 = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.city = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.nation = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.gender = reader.int32() as any;
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.dateOfBirth = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.customer = CreateCustomerCommand.decode(reader, reader.uint32());
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.shipper = CreateShipperCommand.decode(reader, reader.uint32());
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.shopOwner = CreateCustomerCommand.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateUserRequest {
    return {
      firstName: isSet(object.firstName) ? globalThis.String(object.firstName) : "",
      lastName: isSet(object.lastName) ? globalThis.String(object.lastName) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      phoneNumber: isSet(object.phoneNumber) ? globalThis.String(object.phoneNumber) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      addressLine1: isSet(object.addressLine1) ? globalThis.String(object.addressLine1) : "",
      addressLine2: isSet(object.addressLine2) ? globalThis.String(object.addressLine2) : "",
      city: isSet(object.city) ? globalThis.String(object.city) : "",
      nation: isSet(object.nation) ? globalThis.String(object.nation) : "",
      gender: isSet(object.gender) ? genderFromJSON(object.gender) : 0,
      role: isSet(object.role) ? roleFromJSON(object.role) : 0,
      dateOfBirth: isSet(object.dateOfBirth) ? fromJsonTimestamp(object.dateOfBirth) : undefined,
      customer: isSet(object.customer) ? CreateCustomerCommand.fromJSON(object.customer) : undefined,
      shipper: isSet(object.shipper) ? CreateShipperCommand.fromJSON(object.shipper) : undefined,
      shopOwner: isSet(object.shopOwner) ? CreateCustomerCommand.fromJSON(object.shopOwner) : undefined,
    };
  },

  toJSON(message: CreateUserRequest): unknown {
    const obj: any = {};
    if (message.firstName !== "") {
      obj.firstName = message.firstName;
    }
    if (message.lastName !== "") {
      obj.lastName = message.lastName;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.phoneNumber !== "") {
      obj.phoneNumber = message.phoneNumber;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.addressLine1 !== "") {
      obj.addressLine1 = message.addressLine1;
    }
    if (message.addressLine2 !== "") {
      obj.addressLine2 = message.addressLine2;
    }
    if (message.city !== "") {
      obj.city = message.city;
    }
    if (message.nation !== "") {
      obj.nation = message.nation;
    }
    if (message.gender !== 0) {
      obj.gender = genderToJSON(message.gender);
    }
    if (message.role !== 0) {
      obj.role = roleToJSON(message.role);
    }
    if (message.dateOfBirth !== undefined) {
      obj.dateOfBirth = message.dateOfBirth.toISOString();
    }
    if (message.customer !== undefined) {
      obj.customer = CreateCustomerCommand.toJSON(message.customer);
    }
    if (message.shipper !== undefined) {
      obj.shipper = CreateShipperCommand.toJSON(message.shipper);
    }
    if (message.shopOwner !== undefined) {
      obj.shopOwner = CreateCustomerCommand.toJSON(message.shopOwner);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateUserRequest>, I>>(base?: I): CreateUserRequest {
    return CreateUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateUserRequest>, I>>(object: I): CreateUserRequest {
    const message = createBaseCreateUserRequest();
    message.firstName = object.firstName ?? "";
    message.lastName = object.lastName ?? "";
    message.email = object.email ?? "";
    message.phoneNumber = object.phoneNumber ?? "";
    message.username = object.username ?? "";
    message.password = object.password ?? "";
    message.addressLine1 = object.addressLine1 ?? "";
    message.addressLine2 = object.addressLine2 ?? "";
    message.city = object.city ?? "";
    message.nation = object.nation ?? "";
    message.gender = object.gender ?? 0;
    message.role = object.role ?? 0;
    message.dateOfBirth = object.dateOfBirth ?? undefined;
    message.customer = (object.customer !== undefined && object.customer !== null)
      ? CreateCustomerCommand.fromPartial(object.customer)
      : undefined;
    message.shipper = (object.shipper !== undefined && object.shipper !== null)
      ? CreateShipperCommand.fromPartial(object.shipper)
      : undefined;
    message.shopOwner = (object.shopOwner !== undefined && object.shopOwner !== null)
      ? CreateCustomerCommand.fromPartial(object.shopOwner)
      : undefined;
    return message;
  },
};

function createBaseCreateCustomerCommand(): CreateCustomerCommand {
  return {};
}

export const CreateCustomerCommand: MessageFns<CreateCustomerCommand> = {
  encode(_: CreateCustomerCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateCustomerCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateCustomerCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CreateCustomerCommand {
    return {};
  },

  toJSON(_: CreateCustomerCommand): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateCustomerCommand>, I>>(base?: I): CreateCustomerCommand {
    return CreateCustomerCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateCustomerCommand>, I>>(_: I): CreateCustomerCommand {
    const message = createBaseCreateCustomerCommand();
    return message;
  },
};

function createBaseCreateShopOwnerCommand(): CreateShopOwnerCommand {
  return {};
}

export const CreateShopOwnerCommand: MessageFns<CreateShopOwnerCommand> = {
  encode(_: CreateShopOwnerCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateShopOwnerCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateShopOwnerCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CreateShopOwnerCommand {
    return {};
  },

  toJSON(_: CreateShopOwnerCommand): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateShopOwnerCommand>, I>>(base?: I): CreateShopOwnerCommand {
    return CreateShopOwnerCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateShopOwnerCommand>, I>>(_: I): CreateShopOwnerCommand {
    const message = createBaseCreateShopOwnerCommand();
    return message;
  },
};

function createBaseCreateShipperCommand(): CreateShipperCommand {
  return { shipmentInventoryId: "" };
}

export const CreateShipperCommand: MessageFns<CreateShipperCommand> = {
  encode(message: CreateShipperCommand, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.shipmentInventoryId !== "") {
      writer.uint32(10).string(message.shipmentInventoryId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateShipperCommand {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateShipperCommand();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.shipmentInventoryId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateShipperCommand {
    return {
      shipmentInventoryId: isSet(object.shipmentInventoryId) ? globalThis.String(object.shipmentInventoryId) : "",
    };
  },

  toJSON(message: CreateShipperCommand): unknown {
    const obj: any = {};
    if (message.shipmentInventoryId !== "") {
      obj.shipmentInventoryId = message.shipmentInventoryId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateShipperCommand>, I>>(base?: I): CreateShipperCommand {
    return CreateShipperCommand.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateShipperCommand>, I>>(object: I): CreateShipperCommand {
    const message = createBaseCreateShipperCommand();
    message.shipmentInventoryId = object.shipmentInventoryId ?? "";
    return message;
  },
};

function createBaseCustomer(): Customer {
  return { point: 0 };
}

export const Customer: MessageFns<Customer> = {
  encode(message: Customer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.point !== 0) {
      writer.uint32(8).uint64(message.point);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Customer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCustomer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.point = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Customer {
    return { point: isSet(object.point) ? globalThis.Number(object.point) : 0 };
  },

  toJSON(message: Customer): unknown {
    const obj: any = {};
    if (message.point !== 0) {
      obj.point = Math.round(message.point);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Customer>, I>>(base?: I): Customer {
    return Customer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Customer>, I>>(object: I): Customer {
    const message = createBaseCustomer();
    message.point = object.point ?? 0;
    return message;
  },
};

function createBaseShipper(): Shipper {
  return { shipmentInventoryId: "" };
}

export const Shipper: MessageFns<Shipper> = {
  encode(message: Shipper, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.shipmentInventoryId !== "") {
      writer.uint32(10).string(message.shipmentInventoryId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Shipper {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseShipper();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.shipmentInventoryId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Shipper {
    return {
      shipmentInventoryId: isSet(object.shipmentInventoryId) ? globalThis.String(object.shipmentInventoryId) : "",
    };
  },

  toJSON(message: Shipper): unknown {
    const obj: any = {};
    if (message.shipmentInventoryId !== "") {
      obj.shipmentInventoryId = message.shipmentInventoryId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Shipper>, I>>(base?: I): Shipper {
    return Shipper.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Shipper>, I>>(object: I): Shipper {
    const message = createBaseShipper();
    message.shipmentInventoryId = object.shipmentInventoryId ?? "";
    return message;
  },
};

function createBaseShopOwner(): ShopOwner {
  return { numOfShop: 0 };
}

export const ShopOwner: MessageFns<ShopOwner> = {
  encode(message: ShopOwner, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.numOfShop !== 0) {
      writer.uint32(8).uint64(message.numOfShop);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ShopOwner {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseShopOwner();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.numOfShop = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ShopOwner {
    return { numOfShop: isSet(object.numOfShop) ? globalThis.Number(object.numOfShop) : 0 };
  },

  toJSON(message: ShopOwner): unknown {
    const obj: any = {};
    if (message.numOfShop !== 0) {
      obj.numOfShop = Math.round(message.numOfShop);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ShopOwner>, I>>(base?: I): ShopOwner {
    return ShopOwner.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ShopOwner>, I>>(object: I): ShopOwner {
    const message = createBaseShopOwner();
    message.numOfShop = object.numOfShop ?? 0;
    return message;
  },
};

function createBaseCreateUserResponse(): CreateUserResponse {
  return {
    id: "",
    firstName: "",
    lastName: "",
    email: "",
    phoneNumber: "",
    username: "",
    addressLine1: "",
    addressLine2: undefined,
    city: "",
    nation: "",
    gender: 0,
    role: 0,
    dateOfBirth: undefined,
    customer: undefined,
    shipper: undefined,
    shopOwner: undefined,
  };
}

export const CreateUserResponse: MessageFns<CreateUserResponse> = {
  encode(message: CreateUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.firstName !== "") {
      writer.uint32(18).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(26).string(message.lastName);
    }
    if (message.email !== "") {
      writer.uint32(34).string(message.email);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(42).string(message.phoneNumber);
    }
    if (message.username !== "") {
      writer.uint32(50).string(message.username);
    }
    if (message.addressLine1 !== "") {
      writer.uint32(58).string(message.addressLine1);
    }
    if (message.addressLine2 !== undefined) {
      writer.uint32(66).string(message.addressLine2);
    }
    if (message.city !== "") {
      writer.uint32(74).string(message.city);
    }
    if (message.nation !== "") {
      writer.uint32(82).string(message.nation);
    }
    if (message.gender !== 0) {
      writer.uint32(88).int32(message.gender);
    }
    if (message.role !== 0) {
      writer.uint32(96).int32(message.role);
    }
    if (message.dateOfBirth !== undefined) {
      Timestamp.encode(toTimestamp(message.dateOfBirth), writer.uint32(106).fork()).join();
    }
    if (message.customer !== undefined) {
      Customer.encode(message.customer, writer.uint32(114).fork()).join();
    }
    if (message.shipper !== undefined) {
      Shipper.encode(message.shipper, writer.uint32(122).fork()).join();
    }
    if (message.shopOwner !== undefined) {
      ShopOwner.encode(message.shopOwner, writer.uint32(130).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.addressLine1 = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.addressLine2 = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.city = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.nation = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.gender = reader.int32() as any;
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.dateOfBirth = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.customer = Customer.decode(reader, reader.uint32());
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.shipper = Shipper.decode(reader, reader.uint32());
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.shopOwner = ShopOwner.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateUserResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      firstName: isSet(object.firstName) ? globalThis.String(object.firstName) : "",
      lastName: isSet(object.lastName) ? globalThis.String(object.lastName) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      phoneNumber: isSet(object.phoneNumber) ? globalThis.String(object.phoneNumber) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      addressLine1: isSet(object.addressLine1) ? globalThis.String(object.addressLine1) : "",
      addressLine2: isSet(object.addressLine2) ? globalThis.String(object.addressLine2) : undefined,
      city: isSet(object.city) ? globalThis.String(object.city) : "",
      nation: isSet(object.nation) ? globalThis.String(object.nation) : "",
      gender: isSet(object.gender) ? genderFromJSON(object.gender) : 0,
      role: isSet(object.role) ? roleFromJSON(object.role) : 0,
      dateOfBirth: isSet(object.dateOfBirth) ? fromJsonTimestamp(object.dateOfBirth) : undefined,
      customer: isSet(object.customer) ? Customer.fromJSON(object.customer) : undefined,
      shipper: isSet(object.shipper) ? Shipper.fromJSON(object.shipper) : undefined,
      shopOwner: isSet(object.shopOwner) ? ShopOwner.fromJSON(object.shopOwner) : undefined,
    };
  },

  toJSON(message: CreateUserResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.firstName !== "") {
      obj.firstName = message.firstName;
    }
    if (message.lastName !== "") {
      obj.lastName = message.lastName;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.phoneNumber !== "") {
      obj.phoneNumber = message.phoneNumber;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.addressLine1 !== "") {
      obj.addressLine1 = message.addressLine1;
    }
    if (message.addressLine2 !== undefined) {
      obj.addressLine2 = message.addressLine2;
    }
    if (message.city !== "") {
      obj.city = message.city;
    }
    if (message.nation !== "") {
      obj.nation = message.nation;
    }
    if (message.gender !== 0) {
      obj.gender = genderToJSON(message.gender);
    }
    if (message.role !== 0) {
      obj.role = roleToJSON(message.role);
    }
    if (message.dateOfBirth !== undefined) {
      obj.dateOfBirth = message.dateOfBirth.toISOString();
    }
    if (message.customer !== undefined) {
      obj.customer = Customer.toJSON(message.customer);
    }
    if (message.shipper !== undefined) {
      obj.shipper = Shipper.toJSON(message.shipper);
    }
    if (message.shopOwner !== undefined) {
      obj.shopOwner = ShopOwner.toJSON(message.shopOwner);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateUserResponse>, I>>(base?: I): CreateUserResponse {
    return CreateUserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateUserResponse>, I>>(object: I): CreateUserResponse {
    const message = createBaseCreateUserResponse();
    message.id = object.id ?? "";
    message.firstName = object.firstName ?? "";
    message.lastName = object.lastName ?? "";
    message.email = object.email ?? "";
    message.phoneNumber = object.phoneNumber ?? "";
    message.username = object.username ?? "";
    message.addressLine1 = object.addressLine1 ?? "";
    message.addressLine2 = object.addressLine2 ?? undefined;
    message.city = object.city ?? "";
    message.nation = object.nation ?? "";
    message.gender = object.gender ?? 0;
    message.role = object.role ?? 0;
    message.dateOfBirth = object.dateOfBirth ?? undefined;
    message.customer = (object.customer !== undefined && object.customer !== null)
      ? Customer.fromPartial(object.customer)
      : undefined;
    message.shipper = (object.shipper !== undefined && object.shipper !== null)
      ? Shipper.fromPartial(object.shipper)
      : undefined;
    message.shopOwner = (object.shopOwner !== undefined && object.shopOwner !== null)
      ? ShopOwner.fromPartial(object.shopOwner)
      : undefined;
    return message;
  },
};

function createBaseUpdateUserInfoRequest(): UpdateUserInfoRequest {
  return {
    firstName: undefined,
    lastName: undefined,
    phoneNumber: undefined,
    addressLine1: undefined,
    addressLine2: undefined,
    city: undefined,
    nation: undefined,
    gender: undefined,
    role: undefined,
    dateOfBirth: undefined,
    customer: undefined,
    shipper: undefined,
    shopOwner: undefined,
  };
}

export const UpdateUserInfoRequest: MessageFns<UpdateUserInfoRequest> = {
  encode(message: UpdateUserInfoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.firstName !== undefined) {
      writer.uint32(10).string(message.firstName);
    }
    if (message.lastName !== undefined) {
      writer.uint32(18).string(message.lastName);
    }
    if (message.phoneNumber !== undefined) {
      writer.uint32(26).string(message.phoneNumber);
    }
    if (message.addressLine1 !== undefined) {
      writer.uint32(34).string(message.addressLine1);
    }
    if (message.addressLine2 !== undefined) {
      writer.uint32(42).string(message.addressLine2);
    }
    if (message.city !== undefined) {
      writer.uint32(50).string(message.city);
    }
    if (message.nation !== undefined) {
      writer.uint32(58).string(message.nation);
    }
    if (message.gender !== undefined) {
      writer.uint32(64).int32(message.gender);
    }
    if (message.role !== undefined) {
      writer.uint32(72).int32(message.role);
    }
    if (message.dateOfBirth !== undefined) {
      Timestamp.encode(toTimestamp(message.dateOfBirth), writer.uint32(82).fork()).join();
    }
    if (message.customer !== undefined) {
      UpdateCustomerRequest.encode(message.customer, writer.uint32(90).fork()).join();
    }
    if (message.shipper !== undefined) {
      UpdateShipperRequest.encode(message.shipper, writer.uint32(98).fork()).join();
    }
    if (message.shopOwner !== undefined) {
      UpdateShopOwnerRequest.encode(message.shopOwner, writer.uint32(106).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUserInfoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUserInfoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.addressLine1 = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.addressLine2 = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.city = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.nation = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.gender = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.dateOfBirth = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.customer = UpdateCustomerRequest.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.shipper = UpdateShipperRequest.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.shopOwner = UpdateShopOwnerRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateUserInfoRequest {
    return {
      firstName: isSet(object.firstName) ? globalThis.String(object.firstName) : undefined,
      lastName: isSet(object.lastName) ? globalThis.String(object.lastName) : undefined,
      phoneNumber: isSet(object.phoneNumber) ? globalThis.String(object.phoneNumber) : undefined,
      addressLine1: isSet(object.addressLine1) ? globalThis.String(object.addressLine1) : undefined,
      addressLine2: isSet(object.addressLine2) ? globalThis.String(object.addressLine2) : undefined,
      city: isSet(object.city) ? globalThis.String(object.city) : undefined,
      nation: isSet(object.nation) ? globalThis.String(object.nation) : undefined,
      gender: isSet(object.gender) ? genderFromJSON(object.gender) : undefined,
      role: isSet(object.role) ? roleFromJSON(object.role) : undefined,
      dateOfBirth: isSet(object.dateOfBirth) ? fromJsonTimestamp(object.dateOfBirth) : undefined,
      customer: isSet(object.customer) ? UpdateCustomerRequest.fromJSON(object.customer) : undefined,
      shipper: isSet(object.shipper) ? UpdateShipperRequest.fromJSON(object.shipper) : undefined,
      shopOwner: isSet(object.shopOwner) ? UpdateShopOwnerRequest.fromJSON(object.shopOwner) : undefined,
    };
  },

  toJSON(message: UpdateUserInfoRequest): unknown {
    const obj: any = {};
    if (message.firstName !== undefined) {
      obj.firstName = message.firstName;
    }
    if (message.lastName !== undefined) {
      obj.lastName = message.lastName;
    }
    if (message.phoneNumber !== undefined) {
      obj.phoneNumber = message.phoneNumber;
    }
    if (message.addressLine1 !== undefined) {
      obj.addressLine1 = message.addressLine1;
    }
    if (message.addressLine2 !== undefined) {
      obj.addressLine2 = message.addressLine2;
    }
    if (message.city !== undefined) {
      obj.city = message.city;
    }
    if (message.nation !== undefined) {
      obj.nation = message.nation;
    }
    if (message.gender !== undefined) {
      obj.gender = genderToJSON(message.gender);
    }
    if (message.role !== undefined) {
      obj.role = roleToJSON(message.role);
    }
    if (message.dateOfBirth !== undefined) {
      obj.dateOfBirth = message.dateOfBirth.toISOString();
    }
    if (message.customer !== undefined) {
      obj.customer = UpdateCustomerRequest.toJSON(message.customer);
    }
    if (message.shipper !== undefined) {
      obj.shipper = UpdateShipperRequest.toJSON(message.shipper);
    }
    if (message.shopOwner !== undefined) {
      obj.shopOwner = UpdateShopOwnerRequest.toJSON(message.shopOwner);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateUserInfoRequest>, I>>(base?: I): UpdateUserInfoRequest {
    return UpdateUserInfoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateUserInfoRequest>, I>>(object: I): UpdateUserInfoRequest {
    const message = createBaseUpdateUserInfoRequest();
    message.firstName = object.firstName ?? undefined;
    message.lastName = object.lastName ?? undefined;
    message.phoneNumber = object.phoneNumber ?? undefined;
    message.addressLine1 = object.addressLine1 ?? undefined;
    message.addressLine2 = object.addressLine2 ?? undefined;
    message.city = object.city ?? undefined;
    message.nation = object.nation ?? undefined;
    message.gender = object.gender ?? undefined;
    message.role = object.role ?? undefined;
    message.dateOfBirth = object.dateOfBirth ?? undefined;
    message.customer = (object.customer !== undefined && object.customer !== null)
      ? UpdateCustomerRequest.fromPartial(object.customer)
      : undefined;
    message.shipper = (object.shipper !== undefined && object.shipper !== null)
      ? UpdateShipperRequest.fromPartial(object.shipper)
      : undefined;
    message.shopOwner = (object.shopOwner !== undefined && object.shopOwner !== null)
      ? UpdateShopOwnerRequest.fromPartial(object.shopOwner)
      : undefined;
    return message;
  },
};

function createBaseUpdateCustomerRequest(): UpdateCustomerRequest {
  return {};
}

export const UpdateCustomerRequest: MessageFns<UpdateCustomerRequest> = {
  encode(_: UpdateCustomerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateCustomerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateCustomerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): UpdateCustomerRequest {
    return {};
  },

  toJSON(_: UpdateCustomerRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateCustomerRequest>, I>>(base?: I): UpdateCustomerRequest {
    return UpdateCustomerRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateCustomerRequest>, I>>(_: I): UpdateCustomerRequest {
    const message = createBaseUpdateCustomerRequest();
    return message;
  },
};

function createBaseUpdateShipperRequest(): UpdateShipperRequest {
  return { shipmentInventoryId: undefined };
}

export const UpdateShipperRequest: MessageFns<UpdateShipperRequest> = {
  encode(message: UpdateShipperRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.shipmentInventoryId !== undefined) {
      writer.uint32(10).string(message.shipmentInventoryId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateShipperRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateShipperRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.shipmentInventoryId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateShipperRequest {
    return {
      shipmentInventoryId: isSet(object.shipmentInventoryId)
        ? globalThis.String(object.shipmentInventoryId)
        : undefined,
    };
  },

  toJSON(message: UpdateShipperRequest): unknown {
    const obj: any = {};
    if (message.shipmentInventoryId !== undefined) {
      obj.shipmentInventoryId = message.shipmentInventoryId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateShipperRequest>, I>>(base?: I): UpdateShipperRequest {
    return UpdateShipperRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateShipperRequest>, I>>(object: I): UpdateShipperRequest {
    const message = createBaseUpdateShipperRequest();
    message.shipmentInventoryId = object.shipmentInventoryId ?? undefined;
    return message;
  },
};

function createBaseUpdateShopOwnerRequest(): UpdateShopOwnerRequest {
  return {};
}

export const UpdateShopOwnerRequest: MessageFns<UpdateShopOwnerRequest> = {
  encode(_: UpdateShopOwnerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateShopOwnerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateShopOwnerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): UpdateShopOwnerRequest {
    return {};
  },

  toJSON(_: UpdateShopOwnerRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateShopOwnerRequest>, I>>(base?: I): UpdateShopOwnerRequest {
    return UpdateShopOwnerRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateShopOwnerRequest>, I>>(_: I): UpdateShopOwnerRequest {
    const message = createBaseUpdateShopOwnerRequest();
    return message;
  },
};

function createBaseUpdateUserRequest(): UpdateUserRequest {
  return { userId: undefined, updateInfo: undefined };
}

export const UpdateUserRequest: MessageFns<UpdateUserRequest> = {
  encode(message: UpdateUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== undefined) {
      UserId.encode(message.userId, writer.uint32(10).fork()).join();
    }
    if (message.updateInfo !== undefined) {
      UpdateUserInfoRequest.encode(message.updateInfo, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = UserId.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.updateInfo = UpdateUserInfoRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateUserRequest {
    return {
      userId: isSet(object.userId) ? UserId.fromJSON(object.userId) : undefined,
      updateInfo: isSet(object.updateInfo) ? UpdateUserInfoRequest.fromJSON(object.updateInfo) : undefined,
    };
  },

  toJSON(message: UpdateUserRequest): unknown {
    const obj: any = {};
    if (message.userId !== undefined) {
      obj.userId = UserId.toJSON(message.userId);
    }
    if (message.updateInfo !== undefined) {
      obj.updateInfo = UpdateUserInfoRequest.toJSON(message.updateInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateUserRequest>, I>>(base?: I): UpdateUserRequest {
    return UpdateUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateUserRequest>, I>>(object: I): UpdateUserRequest {
    const message = createBaseUpdateUserRequest();
    message.userId = (object.userId !== undefined && object.userId !== null)
      ? UserId.fromPartial(object.userId)
      : undefined;
    message.updateInfo = (object.updateInfo !== undefined && object.updateInfo !== null)
      ? UpdateUserInfoRequest.fromPartial(object.updateInfo)
      : undefined;
    return message;
  },
};

function createBaseUpdateUserResponse(): UpdateUserResponse {
  return {
    id: "",
    firstName: "",
    lastName: "",
    phoneNumber: "",
    addressLine1: "",
    addressLine2: undefined,
    city: "",
    nation: "",
    gender: 0,
    role: 0,
    dateOfBirth: undefined,
    customer: undefined,
    shipper: undefined,
    shopOwner: undefined,
  };
}

export const UpdateUserResponse: MessageFns<UpdateUserResponse> = {
  encode(message: UpdateUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.firstName !== "") {
      writer.uint32(18).string(message.firstName);
    }
    if (message.lastName !== "") {
      writer.uint32(26).string(message.lastName);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(34).string(message.phoneNumber);
    }
    if (message.addressLine1 !== "") {
      writer.uint32(42).string(message.addressLine1);
    }
    if (message.addressLine2 !== undefined) {
      writer.uint32(50).string(message.addressLine2);
    }
    if (message.city !== "") {
      writer.uint32(58).string(message.city);
    }
    if (message.nation !== "") {
      writer.uint32(66).string(message.nation);
    }
    if (message.gender !== 0) {
      writer.uint32(72).int32(message.gender);
    }
    if (message.role !== 0) {
      writer.uint32(80).int32(message.role);
    }
    if (message.dateOfBirth !== undefined) {
      Timestamp.encode(toTimestamp(message.dateOfBirth), writer.uint32(90).fork()).join();
    }
    if (message.customer !== undefined) {
      Customer.encode(message.customer, writer.uint32(98).fork()).join();
    }
    if (message.shipper !== undefined) {
      Shipper.encode(message.shipper, writer.uint32(106).fork()).join();
    }
    if (message.shopOwner !== undefined) {
      ShopOwner.encode(message.shopOwner, writer.uint32(114).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.firstName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.lastName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.addressLine1 = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.addressLine2 = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.city = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.nation = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.gender = reader.int32() as any;
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.dateOfBirth = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.customer = Customer.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.shipper = Shipper.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.shopOwner = ShopOwner.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateUserResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      firstName: isSet(object.firstName) ? globalThis.String(object.firstName) : "",
      lastName: isSet(object.lastName) ? globalThis.String(object.lastName) : "",
      phoneNumber: isSet(object.phoneNumber) ? globalThis.String(object.phoneNumber) : "",
      addressLine1: isSet(object.addressLine1) ? globalThis.String(object.addressLine1) : "",
      addressLine2: isSet(object.addressLine2) ? globalThis.String(object.addressLine2) : undefined,
      city: isSet(object.city) ? globalThis.String(object.city) : "",
      nation: isSet(object.nation) ? globalThis.String(object.nation) : "",
      gender: isSet(object.gender) ? genderFromJSON(object.gender) : 0,
      role: isSet(object.role) ? roleFromJSON(object.role) : 0,
      dateOfBirth: isSet(object.dateOfBirth) ? fromJsonTimestamp(object.dateOfBirth) : undefined,
      customer: isSet(object.customer) ? Customer.fromJSON(object.customer) : undefined,
      shipper: isSet(object.shipper) ? Shipper.fromJSON(object.shipper) : undefined,
      shopOwner: isSet(object.shopOwner) ? ShopOwner.fromJSON(object.shopOwner) : undefined,
    };
  },

  toJSON(message: UpdateUserResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.firstName !== "") {
      obj.firstName = message.firstName;
    }
    if (message.lastName !== "") {
      obj.lastName = message.lastName;
    }
    if (message.phoneNumber !== "") {
      obj.phoneNumber = message.phoneNumber;
    }
    if (message.addressLine1 !== "") {
      obj.addressLine1 = message.addressLine1;
    }
    if (message.addressLine2 !== undefined) {
      obj.addressLine2 = message.addressLine2;
    }
    if (message.city !== "") {
      obj.city = message.city;
    }
    if (message.nation !== "") {
      obj.nation = message.nation;
    }
    if (message.gender !== 0) {
      obj.gender = genderToJSON(message.gender);
    }
    if (message.role !== 0) {
      obj.role = roleToJSON(message.role);
    }
    if (message.dateOfBirth !== undefined) {
      obj.dateOfBirth = message.dateOfBirth.toISOString();
    }
    if (message.customer !== undefined) {
      obj.customer = Customer.toJSON(message.customer);
    }
    if (message.shipper !== undefined) {
      obj.shipper = Shipper.toJSON(message.shipper);
    }
    if (message.shopOwner !== undefined) {
      obj.shopOwner = ShopOwner.toJSON(message.shopOwner);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateUserResponse>, I>>(base?: I): UpdateUserResponse {
    return UpdateUserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateUserResponse>, I>>(object: I): UpdateUserResponse {
    const message = createBaseUpdateUserResponse();
    message.id = object.id ?? "";
    message.firstName = object.firstName ?? "";
    message.lastName = object.lastName ?? "";
    message.phoneNumber = object.phoneNumber ?? "";
    message.addressLine1 = object.addressLine1 ?? "";
    message.addressLine2 = object.addressLine2 ?? undefined;
    message.city = object.city ?? "";
    message.nation = object.nation ?? "";
    message.gender = object.gender ?? 0;
    message.role = object.role ?? 0;
    message.dateOfBirth = object.dateOfBirth ?? undefined;
    message.customer = (object.customer !== undefined && object.customer !== null)
      ? Customer.fromPartial(object.customer)
      : undefined;
    message.shipper = (object.shipper !== undefined && object.shipper !== null)
      ? Shipper.fromPartial(object.shipper)
      : undefined;
    message.shopOwner = (object.shopOwner !== undefined && object.shopOwner !== null)
      ? ShopOwner.fromPartial(object.shopOwner)
      : undefined;
    return message;
  },
};

function createBaseChangePasswordRequest(): ChangePasswordRequest {
  return { userId: "", oldPassword: "", newPassword: "" };
}

export const ChangePasswordRequest: MessageFns<ChangePasswordRequest> = {
  encode(message: ChangePasswordRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.oldPassword !== "") {
      writer.uint32(18).string(message.oldPassword);
    }
    if (message.newPassword !== "") {
      writer.uint32(26).string(message.newPassword);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangePasswordRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangePasswordRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.oldPassword = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.newPassword = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChangePasswordRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      oldPassword: isSet(object.oldPassword) ? globalThis.String(object.oldPassword) : "",
      newPassword: isSet(object.newPassword) ? globalThis.String(object.newPassword) : "",
    };
  },

  toJSON(message: ChangePasswordRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.oldPassword !== "") {
      obj.oldPassword = message.oldPassword;
    }
    if (message.newPassword !== "") {
      obj.newPassword = message.newPassword;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChangePasswordRequest>, I>>(base?: I): ChangePasswordRequest {
    return ChangePasswordRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangePasswordRequest>, I>>(object: I): ChangePasswordRequest {
    const message = createBaseChangePasswordRequest();
    message.userId = object.userId ?? "";
    message.oldPassword = object.oldPassword ?? "";
    message.newPassword = object.newPassword ?? "";
    return message;
  },
};

function createBaseUpdateRefreshTokenRequest(): UpdateRefreshTokenRequest {
  return { userId: "", refreshToken: "" };
}

export const UpdateRefreshTokenRequest: MessageFns<UpdateRefreshTokenRequest> = {
  encode(message: UpdateRefreshTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.refreshToken !== "") {
      writer.uint32(18).string(message.refreshToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateRefreshTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateRefreshTokenRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.refreshToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateRefreshTokenRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      refreshToken: isSet(object.refreshToken) ? globalThis.String(object.refreshToken) : "",
    };
  },

  toJSON(message: UpdateRefreshTokenRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.refreshToken !== "") {
      obj.refreshToken = message.refreshToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateRefreshTokenRequest>, I>>(base?: I): UpdateRefreshTokenRequest {
    return UpdateRefreshTokenRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateRefreshTokenRequest>, I>>(object: I): UpdateRefreshTokenRequest {
    const message = createBaseUpdateRefreshTokenRequest();
    message.userId = object.userId ?? "";
    message.refreshToken = object.refreshToken ?? "";
    return message;
  },
};

function createBaseValidateUserRequest(): ValidateUserRequest {
  return { username: "", password: "" };
}

export const ValidateUserRequest: MessageFns<ValidateUserRequest> = {
  encode(message: ValidateUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateUserRequest {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
    };
  },

  toJSON(message: ValidateUserRequest): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateUserRequest>, I>>(base?: I): ValidateUserRequest {
    return ValidateUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateUserRequest>, I>>(object: I): ValidateUserRequest {
    const message = createBaseValidateUserRequest();
    message.username = object.username ?? "";
    message.password = object.password ?? "";
    return message;
  },
};

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

export type UsersServiceService = typeof UsersServiceService;
export const UsersServiceService = {
  createUser: {
    path: "/com.ecommerceapp.v1.users.UsersService/CreateUser",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateUserRequest) => Buffer.from(CreateUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => CreateUserRequest.decode(value),
    responseSerialize: (value: CreateUserResponse) => Buffer.from(CreateUserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => CreateUserResponse.decode(value),
  },
  updateUser: {
    path: "/com.ecommerceapp.v1.users.UsersService/UpdateUser",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateUserRequest) => Buffer.from(UpdateUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UpdateUserRequest.decode(value),
    responseSerialize: (value: UpdateUserResponse) => Buffer.from(UpdateUserResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => UpdateUserResponse.decode(value),
  },
  changePassword: {
    path: "/com.ecommerceapp.v1.users.UsersService/ChangePassword",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ChangePasswordRequest) => Buffer.from(ChangePasswordRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ChangePasswordRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  updateRefreshToken: {
    path: "/com.ecommerceapp.v1.users.UsersService/UpdateRefreshToken",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateRefreshTokenRequest) =>
      Buffer.from(UpdateRefreshTokenRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => UpdateRefreshTokenRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
  validateUser: {
    path: "/com.ecommerceapp.v1.users.UsersService/ValidateUser",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ValidateUserRequest) => Buffer.from(ValidateUserRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => ValidateUserRequest.decode(value),
    responseSerialize: (value: Empty) => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Empty.decode(value),
  },
} as const;

export interface UsersServiceServer extends UntypedServiceImplementation {
  createUser: handleUnaryCall<CreateUserRequest, CreateUserResponse>;
  updateUser: handleUnaryCall<UpdateUserRequest, UpdateUserResponse>;
  changePassword: handleUnaryCall<ChangePasswordRequest, Empty>;
  updateRefreshToken: handleUnaryCall<UpdateRefreshTokenRequest, Empty>;
  validateUser: handleUnaryCall<ValidateUserRequest, Empty>;
}

export interface UsersServiceClient extends Client {
  createUser(
    request: CreateUserRequest,
    callback: (error: ServiceError | null, response: CreateUserResponse) => void,
  ): ClientUnaryCall;
  createUser(
    request: CreateUserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateUserResponse) => void,
  ): ClientUnaryCall;
  createUser(
    request: CreateUserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateUserResponse) => void,
  ): ClientUnaryCall;
  updateUser(
    request: UpdateUserRequest,
    callback: (error: ServiceError | null, response: UpdateUserResponse) => void,
  ): ClientUnaryCall;
  updateUser(
    request: UpdateUserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdateUserResponse) => void,
  ): ClientUnaryCall;
  updateUser(
    request: UpdateUserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdateUserResponse) => void,
  ): ClientUnaryCall;
  changePassword(
    request: ChangePasswordRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  changePassword(
    request: ChangePasswordRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  changePassword(
    request: ChangePasswordRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  updateRefreshToken(
    request: UpdateRefreshTokenRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  updateRefreshToken(
    request: UpdateRefreshTokenRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  updateRefreshToken(
    request: UpdateRefreshTokenRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  validateUser(
    request: ValidateUserRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  validateUser(
    request: ValidateUserRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  validateUser(
    request: ValidateUserRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
}

export const UsersServiceClient = makeGenericClientConstructor(
  UsersServiceService,
  "com.ecommerceapp.v1.users.UsersService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): UsersServiceClient;
  service: typeof UsersServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
